### ISSUE TITLE
Package Manager Configuration

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovatebot/pro#11]
How do I inject package manager configuration into the Renovate image using the Compose deployment method, or for a Heroku-like platform?

**Comment by destroyerofbuilds** [comment]
For example, how do I inject an `.npmrc` file into the Renovate Pro environment so that Renovate uses our `.npmrc` configuration.

**Comment by rarkins** [comment]
Any env variables in Renovate should work here (and I’ll fix if they don’t). Eg RENOVATE_NPMRC ?

**Comment by rarkins** [comment]
Or do you need the actual file?

**Comment by destroyerofbuilds** [comment]
Okay, so I can inject an override for the standard npm registry using `NPM_CONFIG_REGISTRY=https://URL`.

However, I can't inject an environment variable for a scope, such as `@scope`, because the environment variable would be `NPM_CONFIG_@SCOPE:REGISTRY`, and `@` and `:` aren't supported in a shell variable name.

However, you just answered that question, and another question, I had. I should just [use the `npmrc` option](https://renovatebot.com/docs/configuration-reference/configuration-options#npmrc) for Renovate.

My other question was going to be whether `RENOVATE_` environment variables were supported.
