### ISSUE TITLE
Supporting Corporate Self-signed Certificates

### ISSUE THREAD

**Issue by ghost** [renovatebot/pro#12]
For a company that leverages a self-signed root certificate for managing, and signing, internal certificates for HTTPS, how would, or could, that root certificate be exposed in the Renovate Pro container to enable Renovate, the service, to interact with HTTPS URLs that are using certificates signed by the corporate self-signed certificate?

**Comment by rarkins** [comment]
Anything that is essentially "pass-through" to the Node.js processes should be easy to implement. However, I interpret both the mentioned options to require a one or more *files*, whereas I thought your particular setup was environment variables only? It looks like right now that you would be able to use `NODE_EXTRA_CA_CERTS` and point it to a mounted Docker Volume, if you were able to do that.

**Comment by destroyerofbuilds** [comment]
> one or more files

Correct. It would need to point to a file.

> mounted Docker Volume

If we deployed the container to a VM using Docker Compose, then we would be able to mount an external volume. However, in the Heroku case, there's no way to mount a volume containing custom files.

**Comment by rarkins** [comment]
In that case it seems like the (already possible) solution is:
- Set `NODE_EXTRA_CA_CERTS` to point to a file inside the container (e.g. `/usr/src/app/certs.pem`
- Mount the certs to that file

However if your case with env-only, it doesn't seem like there's an easy solution. *Maybe* we could support an additional Pro env variable that contains the contents of the pem file and writes it out to a predefined location on disk. But is such a cert loaded at node startup time (in which case it's too late) or on a "just in time" the first time it's needed?

Also, what is the wider impact here? Is Renovate rejecting those certificates currently? Or is the idea to be able to turn on stricter host checking later? I haven't thought about this before now.

**Comment by destroyerofbuilds** [comment]
> seems like the (already possible) solution is

We looked into that solution, but, as mentioned earlier, our Heroku-like environment does not allow us mount a volume pointing to disk space containing existing files (There's a roadmap for that support, but there is no time frame for when that support will be implemented).

> Maybe we could support an additional Pro env variable that contains the contents of the pem file and writes it out to a predefined location on disk.

That was suggested internally. We were also suggested, internally, to wrap the Renovate image in our own image that includes the self-signed root certificate. The latter is a problem since we would need to configure the `entrypoint`, or `CMD`. Though `docker inspect` can tell us that information, I'm not sure that's officially part of the Pro API.

> But is such a cert loaded at node startup time 

It's loaded as start time.

> Is Renovate rejecting those certificates currently

Node returns an exception - `Error: unable to verify the first certificate`

**Comment by rarkins** [comment]
> wrap the Renovate image in our own image that includes the self-signed root certificate.

This sounds like the simplest way.

Right now the CMD is pretty simple:
```
CMD [ "node", "server" ]
```

My main concern is that if I make it officially part of the API then it means any change to it requires a major version bump, e.g. if one day I need to wrap it in a bash script.

**Comment by rarkins** [comment]
@0xR did you test out `NODE_EXTRA_CA_CERTS` for self-signed certificates?

**Comment by 0xR** [comment]
I did not, I was going to find a way to do this without disabling TLS altogether though.

Seems like this is a good option.

I’m currently working on something else. I am still planning to deploy renovate properly.

**Comment by rarkins** [comment]
Thanks for the feedback. Once someone can confirm that mounting the relevant file + setting the env variable in the container works, I'll add it to documentation and close this issue.

**Comment by rarkins** [comment]
Closing this as it can be done by mounting volumes and set env. If anyone requires a custom Docker build of `renovate/pro`, I can quote it as an add-on service to the base price.
