### ISSUE TITLE
Manage App Description

### ISSUE THREAD

**Issue by ghost** [renovatebot/pro#14]
Have the Renovate Pro service manage the `description` field for the GitHub App on a GHE deployment.

We wrote our own, based quite a bit on a copy&paste of the official Renovate App, but I'd really like to see the description managed for us. The description field is a great way to sell Renovate to our internal engineering community.

**Comment by rarkins** [comment]
If you mean in an automated manner, I'm not sure an app can really do that, i.e. edit "itself". Have you seen anything that suggests it can?

e.g. https://developer.github.com/v3/apps/

**Comment by destroyerofbuilds** [comment]
> If you mean in an automated manner

Yes, I meant in an automated manner. I would prefer not to maintain the App description every time we upgrade the application (just a tedious task, when, in the end, we just want to copy and paste Renovate's existing description)

> Have you seen anything that suggests it can?

I have not seen any API end-points related to the App description. 

I guess I can infer that you have not heard of such an end-point either. Therefore, let me file a request with GitHub for an API end-point.

**Comment by destroyerofbuilds** [comment]
Though you won't have access to it, we have filed support ticket `60463` with GitHub. We'll see where it leads us.

**Comment by rarkins** [comment]
> every time we upgrade the application

I think we have a crossed wire somewhere. As far as I'm aware, you don't *need* to modify anything in GHE when you upgrade the application. I've rarely touched the hosted app description in the past ~1 year. Can you explain more about your assumption?

**Comment by rarkins** [comment]
Closing as I don't plan for Renovate to manage its own app description
