### ISSUE TITLE
Clarifying Questions Around Deployment in AWS.

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/pro#17]
Hello!

I have some clarifying questions because my team is looking to adopt this infrastructure at scale.
1. What is the recommended size of the EC2 instance for running this service?
2. Can we put this service in an AWS Auto Scaling group with multiple nodes that we then balance behind a load balancer to handle high volumes of traffic?
3. Are there any examples of a Kubernetes deployment that could be provided as a starting point?
4. Are there any "blessed" Terraform or CloudFormation configs for deploying this in a viable way at scale?

Not to worry if these things don't exist yet, I'm happy to be the first to do them. Just trying to figure out the details before jumping in.

**Comment by rarkins** [comment]
Hi @Aghassi, thanks for your inquiry. Some short answers:

1. Renovate uses fairly small memory, so therefore even a `t2.micro` can happily run it. However, I found it a bit annoying to have watch CPU credits so switched to "full" CPU VMs in the m* range. I haven't tested whether multi-CPU VMs provide much benefit and run everything on single CPU instances.

2. Renovate Pro is monolithic and cannot scale to more than one node.

3/4. Sorry, not yet

Can you drop me an email to rhys@renovatebot.com to discuss questions 2/3/4 in more detail? I have some planning in these areas but would like to ask some questions first.
