### ISSUE TITLE
Question: Can renovate encryption web used with hosted renovate

### ISSUE THREAD

**Issue by ghost** [renovatebot/pro#264]
Hi. I have a one question relating to hosted Renovate, can encryption web ui from here https://app.renovatebot.com/encrypt
Be used with self hosted renovate or? I guess the question otherway around is will hosted renovate can decrypt config files that are encrypted this public web ui?

**Comment by rarkins** [comment]
> Hi. I have a one question relating to hosted Renovate, can encryption web ui from here [app.renovatebot.com/encrypt](https://app.renovatebot.com/encrypt) Be used with self hosted renovate or? 

Yes, but you need to download the HTML and replace the public key embedded inside it with your own PGP key.

> I guess the question otherway around is will hosted renovate can decrypt config files that are encrypted this public web ui?

No, because you do not have our private key in order to decrypt them
