### ISSUE TITLE
Support global proxies

### ISSUE THREAD

**Issue by rarkins** [renovatebot/pro#42]
Renovate Pro doesn't currently have support for `HTTP_PROXY` and `HTTPS_PROXY` environment variables like the CLI tool has.

**Comment by rarkins** [comment]
The proxy hooks are done during a part of the CLI's init procedure that isn't currently called by Pro, so needs to be explicitly added.

Cc @patrickmarabeas

**Comment by patrickmarabeas** [comment]
Thanks for update.

**Comment by rarkins** [comment]
Are you running renovate/pro@0.15.2 right now? I'm testing this out locally now

**Comment by patrickmarabeas** [comment]
Correct

**Comment by rarkins** [comment]
Can you test out `renovate/pro:0.15.3-pre.1`? It includes only this fix, but I don't have the infrastructure set up just yet to properly test it. You won't see any logs just yet specifically on whether it's activating the proxy or not, but hopefully it's obvious via other messages whether or not it's using your proxy successfully.

**Comment by patrickmarabeas** [comment]
Appears to be using the proxy settings now as without `hostRules` set I get the following error: 
```
INFO: Not authorised to look up docker tags
```

With credentials in place it now succeeds - but with no action taken or logs to indicate what's occurred:

```
INFO: Repository config (repository=###/###)
"configFile": "renovate.json",
"config": {
  "kubernetes": {"fileMatch": ["^config.yaml$"]},
  "hostRules": [
    {"platform": "docker", "username": "_json_key", "password": "***********"}
  ]
}
INFO: Setting hostRules from config (repository=###/###)
INFO: Found kubernetes package files (repository=###/###)
INFO: Processing 0 branches:  (repository=###/###)
INFO: Request stats (repository=###/###)
"rateLimit": null,
"requestCount": 8,
"rateLimitRemaining": null
INFO: Finished repository (repository=###/###)
```

Using `RENOVATE_LOG_LEVEL` of `debug`

**Comment by rarkins** [comment]
Set `LOG_LEVEL=debug` instead of `RENOVATE_LOG_LEVEL=debug`

**Comment by patrickmarabeas** [comment]
Great Issue was ignored major version bumps. New PR successfully created with new version of the dependency.

Thanks for the quick turnaround on the fix!
