### ISSUE TITLE
Global renovate.json config

### ISSUE THREAD

**Issue by patrickmarabeas** [renovatebot/pro#46]
Does the ability to supply global config (renovate.json) exist?

Is it possible to have multiple `hostRules` for docker depending on the registry?

**Comment by patrickmarabeas** [comment]
Latest deploy has `/usr/src/app/config.js` seemingly being used. Unsure why now.

**Comment by rarkins** [comment]
When you administer a bot - whether the OSS CLI tool or Pro - you have three main ways to have "global" config.

The first is that you have a `config.js` volume mounted into the bot's container that it will read upon startup.

The second approach is that you set `onboardingConfig` within the bot's config. This determines what is the default `renovate.json` that the bot proposes in the "Configure Renovate" onboarding PR.

The third approach is that you define an organization-wide config preset, and have repos all reference that.

You might end up combining all three approaches, e.g.

- Your `config.js` includes `onboardingConfig: { extends: ['mypreset'] }`
- Repos merge the onboarding PR and always use `mypreset` as their base config

I recommend that you put "admin" bot config in `config.js` only, because this would be applicable/viewable by the bot admin only. And for all user-visible config, put it in a preset so that users can view it at any time if they are curious.

**Comment by patrickmarabeas** [comment]
Setting `RENOVATE_PRINT_CONFIG` to `true` and giving `onboardingConfig.extends` an arbitrary array value results in logs showing:

```
{
  ...
  onboardingConfig: {},
}
```

Additionally, the application fails to start when moving `RENOVATE_ENDPOINT` to `/usr/src/app/config.js`:

```
modules.exports = {
  endpoint: '###'
}
```

```
ERROR: You must configure RENOVATE_ENDPOINT
```

Setting `RENOVATE_CONFIG_FILE` does not help.


In regards to `onboardingConfig` - I assume this means this is essentially blocked by  renovatebot/pro#43 / renovatebot/renovate#3019 ? Or can I just feed it a POJO?

**Comment by rarkins** [comment]
`onboardingConfig` indeed takes a javascript object, if that's what you mean. i.e. you're not restricted to just using `extends`.

Raised #46 re: `RENOVATE_ENDPOINT`. The validation script currently does not take into consideration the config file.

**Comment by patrickmarabeas** [comment]
OK, I didn't have any noticeable success giving it a POJO, which is why I moved some core config there to have immediate feedback as to whether it was being read.

Issue remains that `config.js` doesn't seem to be read, given that `RENOVATE_PRINT_CONFIG` logs

```
{
  ...
  onboardingConfig: {},
}
```

**Comment by rarkins** [comment]
I'm not lost as to what exact config you're trying and what you're experiencing. Can you summarise again exactly what you are configuring - e.g. what in env and config.js?

**Comment by patrickmarabeas** [comment]
Currently Renovate core is being configured in env vars.

The ultimate problem that we are trying to solve is to abstract the GCR json key file auth from project `renovate.json`'s. (on a side note, the string is far too long to use https://renovatebot.com/encrypt)

`onboardingConfig` is not going to solve this - but in trying to configure Renovate I've found that `config.js` is not being read. Any values provided to `onboardingConfig`, for instance, result in a log output of:

```
{
  ...
  onboardingConfig: {},
}
```

**Comment by rarkins** [comment]
`config.js` seems to being read fine when I test it. 

In my case I'm using Docker Compose, with volumes like this:

```
    volumes:
      - ./github-com-renovate-pro-private-key.pem:/usr/src/app/renovate.private-key.pem
      - ./config.js:/usr/src/app/config.js
```

Upon startup you see something like this:

```
server_1  | DEBUG: Parsing configs
server_1  | DEBUG: File config
server_1  |        "config": {"onboardingConfig": {"semanticCommits": true}}
server_1  | DEBUG: CLI config
server_1  |        "config": {}
server_1  | DEBUG: Env config
server_1  |        "config": {
server_1  |          "hostRules": [],
server_1  |          "logLevel": "debug",
server_1  |          "platform": "github",
server_1  |          "endpoint": "https://api.github.com/",
server_1  |          "token": "***********"
server_1  |        }
server_1  | DEBUG: Combined config
server_1  |        "config": {
server_1  |          "onboardingConfig": {"semanticCommits": true},
server_1  |          "hostRules": [],
server_1  |          "logLevel": "debug",
server_1  |          "platform": "github",
server_1  |          "endpoint": "https://api.github.com/",
server_1  |          "token": "***********"
server_1  |        }
```

If you're not seeing that, it sounds like the config.js is not found within the Pro container. Instead you'll see this:

```
server_1  | DEBUG: File config
server_1  |        "config": {}
```

Either way, I don't recommend putting secrets into your `onboardingConfig` - they should stay on the server side.
