### ISSUE TITLE
Support using `config.js` instead of `RENOVATE_*` variables

### ISSUE THREAD

**Issue by rarkins** [renovatebot/pro#47]
As per documentation and confirmed in https://github.com/renovatebot/pro/issues/46#issuecomment-473723849, Renovate Pro's validation requires `RENOVATE_ENDPOINT` to be set in env only, for example.

Therefore this feature request is to allow the use of `config.js` for env config.

**Comment by rarkins** [comment]
I need to apply the `wontfix` label to this. These env vars are used during Pro bootstrap and before parsing of config.js and it would complicate the codebase too much to change that.

**Comment by patrickmarabeas** [comment]
Please outline the properties which _must_ be set as env vars, and those which can be done in `config.js`

**Comment by rarkins** [comment]
Everything you see in https://github.com/renovatebot/pro/blob/master/docs/configuration-github.md#configure-renovate-pro must be done using env
