### ISSUE TITLE
Support PostgreSQL Database credentials via DATABASE_URL Environment Variable

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovatebot/pro#7]
We would like to deploy the Renovate Pro image on a [Heroku-like Docker platform](https://devcenter.heroku.com/articles/container-registry-and-runtime).

During provisioning of a PostgreSQL database on our infrastructure, a [`DATABASE_URL`](https://devcenter.heroku.com/articles/heroku-postgresql#provisioning-heroku-postgres) environment variable is exposed to the container.

[`DATABASE_URL` contains all necessary credentials](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING) to connect to our PostgreSQL database.

**Comment by rarkins** [comment]
I'm going to go with logic like this, I think/hope it's this simple:

![image](https://user-images.githubusercontent.com/6311784/39319996-124dea40-4983-11e8-9893-6f1d4deb608b.png)

**Comment by rarkins** [comment]
@destroyerofbuilds can you test with [renovate/pro:latest](https://hub.docker.com/r/renovate/pro/tags/)? Pushed a minute or two ago so make sure you pull again and not from cache.

**Comment by destroyerofbuilds** [comment]
I can confirm Renovate Pro is correctly connecting to a PostgreSQL database using the `DATABASE_URL` environment variable.
