### ISSUE TITLE
Not discovering all repositories

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/pro#73]
I'm trying to use 0.17.0, against a self-hosted Gitlab instance

It doesn't appear to be handling pagination properly when getting the list of projects:

```
{"name":"renovate","hostname":"pro-1-79b77998df-6bzl2","pid":1,"level":30,"msg":"jobScheduler running","time":"2019-10-16T16:37:00.002Z","v":0}
{"name":"renovate","hostname":"pro-1-79b77998df-6bzl2","pid":1,"level":30,"msg":"Ignoring non-installed repo","time":"2019-10-16T16:37:04.793Z","v":0}
{"name":"renovate","hostname":"pro-1-79b77998df-6bzl2","pid":1,"level":30,"msg":"Discovered 100 repositories","time":"2019-10-16T16:37:05.115Z","v":0}
```

Looks like it only finds one page of results?

**Comment by mikebryant** [comment]
(I'm kinda surprised it isn't just using the same function as renovate OSS, where this works)

**Comment by rarkins** [comment]
Please see https://github.com/renovatebot/pro/releases/tag/0.18.0-pre.0

**Comment by mikebryant** [comment]
I'm trying 0.18.0-pre.0, but it's still not working for me:

```
 INFO: Discovered 100 repositories
```
