### ISSUE TITLE
Issue PRO vs CLI, private docker registry login

### ISSUE THREAD

**Issue by elpaisa** [renovatebot/pro#75]
Hi,

I'm trying to setup the docker pro image for our organization, everything goes well, except that it can't connect to our private docker repository, i've tried different versions of Renovate pro without success, however if i setup the CLI versions docker, it connects correctly to the private registry, would you mind to point me in the right direction?, i'm using the same configuration for both containers.

Pro versions used: 0.18.0-pre.2, 0.17.0, 0.16.2
CLI versions used: 19.65.9, 19.59.1, 19.52.2

DEBUG: Combined config
```
"config": {
         "platform": "github",
         "logFileLevel": "warn",
         "logLevel": "debug",
         "baseDir": "/tmp/renovate/",
         "cacheDir": "/tmp/renovate/cache/",
         "gitAuthor": "Engineering Services Bot <..>",
         "gitPrivateKey": "***********",
         "onboarding": false,
         "onboardingConfig": {"extends": ["config:base"]},
         "hostRules": [
           {
             "hostType": "docker",
             "hostName": "artifacts....",
             "username": "robot...",
             "password": "***********"
           }
         ],
         "endpoint": "https://api.github.com/"
       }
```

Error trace:
```
"body": {
           "errors": [
             {
               "code": "UNAUTHORIZED",
               "message": "authentication required",
               "detail": [
                 {
                   "Type": "repository",
                   "Class": "",
                   "Name": "....",
                   "Action": "pull"
                 }
               ]
             }
           ]
         },
         "message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at EventEmitter.emitter.on (/usr/src/app/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by rarkins** [comment]
Can you compare the log trace you receive in Pro vs when running the CLI version? e.g. does the config look the same, and is there any difference in the Docker lookup logs?

If you can reproducibly have it working in CLI vs Pro, the next step would be to see if the [renovate/renovate](https://hub.docker.com/r/renovate/renovate) Docker image works or fails.

My goal is to work out whether this is because Pro does not embed the very latest `renovate` version, or because of something inherently in Pro. Realistically 95% of the code in Pro is the same as in the CLI.

**Comment by elpaisa** [comment]
> Can you compare the log trace you receive in Pro vs when running the CLI version? e.g. does the config look the same, and is there any difference in the Docker lookup logs?
> 
> If you can reproducibly have it working in CLI vs Pro, the next step would be to see if the [renovate/renovate](https://hub.docker.com/r/renovate/renovate) Docker image works or fails.
> 
> My goal is to work out whether this is because Pro does not embed the very latest `renovate` version, or because of something inherently in Pro. Realistically 95% of the code in Pro is the same as in the CLI.

Besides `"rangeStrategy": "bump"`, there is no difference in the config log trace, using: `0.18.0-pre.2` vs `19.65.9`

**Comment by rarkins** [comment]
Next step is to rule out that this is caused by any mismatch of Renovate version. Can you test on renovate/pro:0.18.0-pre.3? It has just been published with the latest Renovate included. https://github.com/renovatebot/pro/releases/tag/0.18.0-pre.3

**Comment by rarkins** [comment]
Actually, please try [renovate/pro:0.18.0-pre.4](https://github.com/renovatebot/pro/releases/tag/0.18.0-pre.4) where I have applied a fix that may solve your problem.

**Comment by elpaisa** [comment]
That version solves the issue, thanks for your support!.

**Comment by rarkins** [comment]
Thanks for your help troubleshooting it :)
