### ISSUE TITLE
PrHourlyLimit is always keeping the value of 2

### ISSUE THREAD

**Issue by germandavid85** [renovatebot/pro#76]
Hello

while running `pro:0.18.0-pre.2` as part of the config.js file I am setting the value of

`prHourlyLimit: 6`

and I end with a combined config like:

```
Combined config
server_1  |        "config": {
server_1  |          "platform": "github",
server_1  |          "logFileLevel": "info",
server_1  |          "logLevel": "debug",
server_1  |          "prHourlyLimit": 6,
server_1  |          "baseDir": "/tmp/renovate/",
server_1  |          "token": "***********",
server_1  |          "cacheDir": "/tmp/renovate/cache/",
server_1  |          "githubAuthor": "author<mail@mail.com>",
server_1  |          "onboarding": true,
server_1  |          "onboardingConfig": {"extends": ["config:base"]},
server_1  |          "endpoint": "https://api.github.com/"
server_1  |        }
```

yet, in the debug log I keep seeing `DEBUG: PR hourly limit remaining: 2` no matter if I change the `6` by a `0` it always keeps using `2`

**Comment by rarkins** [comment]
When you set `config:base` as your default config, it includes a rule that sets prHourlyLimit to 2. Any config in the repo takes precedence. You should be able to configure it this way:

```
  "onboardingConfig": {"extends": ["config:base"],"prHourlyLimit":6},
```

But note of course that it won't affect repos you've already onboarded -  you will need to reconfigure them manually.

It can be a good idea for you to have a dedicated repository that contains your own Renovate preset config for your org and use that in your onboardingConfig instead. Then for situations like this you could edit the prHourlyLimit in your preset and it would take effect in all the onboarded repositories.

**Comment by germandavid85** [comment]
thanks for the feedback, I tested overriding the value in the `renovate.json` file and it works, also, I'll give a try to your suggestion of having a dedicated preset config
