### ISSUE TITLE
Gitlab webhook not working 

### ISSUE THREAD

**Issue by alclonky** [renovatebot/pro#85]
If I check the "If you want to rebase/retry ths MR, check this box" checkbox in an renovate MR, the event gets ignored:

Received webhook event (repository=repo)
       "event": "merge_request"
 INFO: Ignoring unimportant MR update

**Comment by rarkins** [comment]
Which Pro version are you using?

If you edit the MR markdown to view its source, what do you see next to the checkbox? e.g. `- [x] <!-- renovate-rebase -->'`

**Comment by alclonky** [comment]
we use 0.18.0

and yes the checkbox is checked when i view the source

**Comment by rarkins** [comment]
I need the exact text in the markdown

**Comment by alclonky** [comment]
`
This MR contains the following updates:

| Package | Update | Change |
|---|---|---|
| ci-mgmt | patch | `1.0.35-gitbfb5e87` -> `1.0.35-gitec140ee` |

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever MR becomes conflicted.

:no_bell: **Ignore**: Close this MR and you won't be reminded about this update again.

---

 - [x] If you want to rebase/retry this MR, check this box

`

**Comment by rarkins** [comment]
In your logs, there should be something printed by this: `logger.info({ event, repository }, 'Received webhook event');`. For this event that's being mistakenly ignored, can you locate the raw `event` from that log message and paste here?

**Comment by alclonky** [comment]
I extracted the json from gitlab 
`{
  "object_kind": "merge_request",
  "event_type": "merge_request",
  "user": {
    "name": "Christian Mustermann",
    "username": "christian.Mustermann",
    "avatar_url": "https://mygitlab.mydomain.com/uploads/-/system/user/avatar/7/avatar.png"
  },
  "project": {
    "id": 158,
    "name": "myrepo",
    "description": "",
    "web_url": "https://mygitlab.mydomain.com/cd/myrepo",
    "avatar_url": "https://mygitlab.mydomain.com/uploads/-/system/project/avatar/158/Logotype_RH_OpenShift_wLogo_RGB_White-cut.png",
    "git_ssh_url": "git@mygitlab.mydomain.com:cd/myrepo.git",
    "git_http_url": "https://mygitlab.mydomain.com/cd/myrepo.git",
    "namespace": "Continuous Deployment",
    "visibility_level": 0,
    "path_with_namespace": "cd/myrepo",
    "default_branch": "master",
    "ci_config_path": null,
    "homepage": "https://mygitlab.mydomain.com/cd/myrepo",
    "url": "git@mygitlab.mydomain.com:cd/myrepo.git",
    "ssh_url": "git@mygitlab.mydomain.com:cd/myrepo.git",
    "http_url": "https://mygitlab.mydomain.com/cd/myrepo.git"
  },
  "object_attributes": {
    "assignee_id": null,
    "author_id": 85,
    "created_at": "2020-01-20 13:18:06 +0100",
    "description": "This MR contains the following updates:\n\n| Package | Update | Change |\n|---|---|---|\n| ci-mgmt-mgmt | patch | `1.0.35-gitbfb5e87` -> `1.0.35-gitec140ee` |\n\n---\n\n### Renovate configuration\n\n:date: **Schedule**: At any time (no schedule defined).\n\n:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n:recycle: **Rebasing**: Whenever MR becomes conflicted.\n\n:no_bell: **Ignore**: Close this MR and you won't be reminded about this update again.\n\n---\n\n - [x] If you want to rebase/retry this MR, check this box",
    "head_pipeline_id": null,
    "id": 12133,
    "iid": 164,
    "last_edited_at": "2020-01-21 10:02:40 +0100",
    "last_edited_by_id": 7,
    "merge_commit_sha": null,
    "merge_error": null,
    "merge_params": {
      "force_remove_source_branch": true
    },
    "merge_status": "can_be_merged",
    "merge_user_id": null,
    "merge_when_pipeline_succeeds": false,
    "milestone_id": null,
    "source_branch": "renovate-ci-mgmt-mgmt-1_x",
    "source_project_id": 158,
    "state_id": 1,
    "target_branch": "master",
    "target_project_id": 158,
    "time_estimate": 0,
    "title": "Update helm chart ci-mgmt-mgmt to v1.0.35-gitec140ee",
    "updated_at": "2020-01-21 10:02:40 +0100",
    "updated_by_id": 7,
    "url": "https://mygitlab.mydomain.com/cd/myrepo/merge_requests/164",
    "source": {
      "id": 158,
      "name": "myrepo",
      "description": "",
      "web_url": "https://mygitlab.mydomain.com/cd/myrepo",
      "avatar_url": "https://mygitlab.mydomain.com/uploads/-/system/project/avatar/158/Logotype_RH_OpenShift_wLogo_RGB_White-cut.png",
      "git_ssh_url": "git@mygitlab.mydomain.com:cd/myrepo.git",
      "git_http_url": "https://mygitlab.mydomain.com/cd/myrepo.git",
      "namespace": "Continuous Deployment",
      "visibility_level": 0,
      "path_with_namespace": "cd/myrepo",
      "default_branch": "master",
      "ci_config_path": null,
      "homepage": "https://mygitlab.mydomain.com/cd/myrepo",
      "url": "git@mygitlab.mydomain.com:cd/myrepo.git",
      "ssh_url": "git@mygitlab.mydomain.com:cd/myrepo.git",
      "http_url": "https://mygitlab.mydomain.com/cd/myrepo.git"
    },
    "target": {
      "id": 158,
      "name": "myrepo",
      "description": "",
      "web_url": "https://mygitlab.mydomain.com/cd/myrepo",
      "avatar_url": "https://mygitlab.mydomain.com/uploads/-/system/project/avatar/158/Logotype_RH_OpenShift_wLogo_RGB_White-cut.png",
      "git_ssh_url": "git@mygitlab.mydomain.com:cd/myrepo.git",
      "git_http_url": "https://mygitlab.mydomain.com/cd/myrepo.git",
      "namespace": "Continuous Deployment",
      "visibility_level": 0,
      "path_with_namespace": "cd/myrepo",
      "default_branch": "master",
      "ci_config_path": null,
      "homepage": "https://mygitlab.mydomain.com/cd/myrepo",
      "url": "git@mygitlab.mydomain.com:cd/myrepo.git",
      "ssh_url": "git@mygitlab.mydomain.com:cd/myrepo.git",
      "http_url": "https://mygitlab.mydomain.com/cd/myrepo.git"
    },
    "last_commit": {
      "id": "cdb5e38cef9ad2aa4f44138ba3bf7c8ac99b3053",
      "message": "Update helm chart ci-mgmt-mgmt to v1.0.35-gitec140ee\n",
      "timestamp": "2020-01-20T19:10:53+00:00",
      "url": "https://mygitlab.mydomain.com/cd/myrepo/commit/cdb5e38cef9ad2aa4f44138ba3bf7c8ac99b3053",
      "author": {
        "name": "Renovate Bot",
        "email": "renovate.bot@mydomain.com"
      }
    },
    "work_in_progress": false,
    "total_time_spent": 0,
    "human_total_time_spent": null,
    "human_time_estimate": null,
    "assignee_ids": [

    ],
    "state": "opened",
    "action": "update"
  },
  "labels": [

  ],
  "changes": {
    "description": {
      "previous": "This MR contains the following updates:\n\n| Package | Update | Change |\n|---|---|---|\n| ci-mgmt-mgmt | patch | `1.0.35-gitbfb5e87` -> `1.0.35-gitec140ee` |\n\n---\n\n### Renovate configuration\n\n:date: **Schedule**: At any time (no schedule defined).\n\n:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n:recycle: **Rebasing**: Whenever MR becomes conflicted.\n\n:no_bell: **Ignore**: Close this MR and you won't be reminded about this update again.\n\n---\n\n - [ ] If you want to rebase/retry this MR, check this box",
      "current": "This MR contains the following updates:\n\n| Package | Update | Change |\n|---|---|---|\n| ci-mgmt-mgmt | patch | `1.0.35-gitbfb5e87` -> `1.0.35-gitec140ee` |\n\n---\n\n### Renovate configuration\n\n:date: **Schedule**: At any time (no schedule defined).\n\n:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n:recycle: **Rebasing**: Whenever MR becomes conflicted.\n\n:no_bell: **Ignore**: Close this MR and you won't be reminded about this update again.\n\n---\n\n - [x] If you want to rebase/retry this MR, check this box"
    },
    "last_edited_at": {
      "previous": "2020-01-21 10:02:34 +0100",
      "current": "2020-01-21 10:02:40 +0100"
    },
    "updated_at": {
      "previous": "2020-01-21 10:02:34 +0100",
      "current": "2020-01-21 10:02:40 +0100"
    }
  },
  "repository": {
    "name": "myrepo",
    "url": "git@mygitlab.mydomain.com:cd/myrepo.git",
    "description": "",
    "homepage": "https://mygitlab.mydomain.com/cd/myrepo"
  }
}`

**Comment by rarkins** [comment]
Can you try 0.18.1? There should be a check that matches the data you provided:

```js
     if (
        state === 'opened' &&
        payload.changes &&
        payload.changes.description &&
        (payload.changes.description.current.includes(
          '- [x] <!-- renovate-rebase -->'
        ))
      ) {
        const reason = 'rebase-request';
        return { task: 'enqueue', repository, reason };
      }
```

**Comment by alclonky** [comment]
with 0.18.1 the webhook is working for us.
is there a changelog for 0.18.1?

Thx for the help

**Comment by rarkins** [comment]
Yes: https://github.com/renovatebot/pro/releases/tag/0.18.1

But I wasn’t aware that the webhook behaviour was changed.
