### ISSUE TITLE
Renovate tries to update an older version of dependency.

### ISSUE THREAD

**Issue by huydinhle** [renovatebot/pro#86]
Our renovate tries to update `json-schema-faker` from `~0.5.0-rc16` -> `~0.5.0-rc9`
<img width="759" alt="Screen Shot 2020-01-24 at 11 59 17 AM" src="https://user-images.githubusercontent.com/20393709/73099792-14551b00-3ea1-11ea-9079-d49b7761593b.png">

**Comment by rarkins** [comment]
The authors of this package have done their versioning incorrectly. Renovate is correct, even if it seems wrong to the human eye.

![image](https://user-images.githubusercontent.com/6311784/73101945-16df6100-3ef1-11ea-92b1-0acc953aef62.png)


Reproduce: https://runkit.com/embed/77p8sf37p20i
