### ISSUE TITLE
[Github Enterprise] White/black listing of orgs/repos

### ISSUE THREAD

**Issue by cricket007** [renovatebot/pro#88]
**Use-case**: We would like to horizontally scale our Renovate instances, such that we have multiple renovate processes working in parallel that are able to scan over specific orgs on their own, or over certain repos more frequently. 

Is this possible?

**Comment by rarkins** [comment]
GitHub or GitLab?

**Comment by cricket007** [comment]
Pretty sure my issue says Github, but why not both?

**Comment by cricket007** [comment]
I see a [`filterConfig`](https://github.com/renovatebot/renovate/blob/master/lib/config/index.ts#L120). Does that do what the name implies?

**Comment by rarkins** [comment]
I missed the prefix in the title. Anyway, the plan we have for this is to extend `autoFilter` support in Pro to GitHub (see #87). Currently this setting is GitLab-only in Pro. Once supported this should mean you can have multiple VMs sharing the same app credentials but splitting up the work based on org/repo patterns.

Will close this in favor of #87

**Comment by cricket007** [comment]
Ah, thanks! 

> Currently this setting is GitLab-only

Maybe the docs should reflect that until the linked issue is complete?
