### ISSUE TITLE
Port Binding

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovatebot/pro#9]
Noticing the following:

```
Web process failed to bind to $PORT within 60 seconds of launch
```

The `compose` example specifically maps to port `8080`, but in our environment the port is set dynamically.

Does Renovate Pro check `$PORT`, or could it check `$PORT`?

**Comment by rarkins** [comment]
Now updated with this logic:
```
  const port = process.env.PORT || 8080;
```

Please pull/try `latest` again.

**Comment by destroyerofbuilds** [comment]
I can confirm Renovate Pro is correctly consuming the `$PORT` environment variable.
